# Generated by Django 3.2.2 on 2022-06-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='cpte', max_length=10, unique=True, verbose_name='cptes')),
            ],
            options={
                'db_table': 'comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='proveedor')),
                ('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
            ],
            options={
                'db_table': 'producto_terminado',
            },
        ),
    ]
