# Generated by Django 3.2.2 on 2022-07-06 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=20, unique=True, verbose_name='tipo')),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medida_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Insumos_Mesa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medida_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'insumos_mesa',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='numero')),
                ('capacidad', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='capacidad')),
                ('descripcion', models.CharField(default='', max_length=60, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Moza_o',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('legajo', models.PositiveIntegerField(default=0, unique=True, verbose_name='legajo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='fecha_ingreso')),
                ('cuil', models.CharField(default='', max_length=80, verbose_name='cuil')),
                ('direccion', models.CharField(default='', max_length=80, verbose_name='direccion')),
                ('telefono', models.CharField(default='', max_length=80, verbose_name='telefono')),
            ],
            options={
                'db_table': 'moza_o',
            },
        ),
        migrations.CreateModel(
            name='ProductoElaborado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('descripcion', models.CharField(default='', max_length=80, verbose_name='descripcion')),
                ('imagen', models.ImageField(default='', null=True, upload_to='productos/', verbose_name='imagen')),
                ('cant_ing_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_base')),
                ('cant_ing_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_2')),
                ('cant_ing_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_3')),
                ('cant_ing_4', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_4')),
                ('cant_ing_5', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_5')),
                ('cant_ing_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_6')),
                ('cant_ing_7', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_7')),
                ('cant_ing_8', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_8')),
                ('cant_ing_9', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_9')),
                ('cant_ing_10', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_10')),
                ('costo_ingred', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo_ingred')),
                ('costo_adic', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo_adic')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo_total')),
                ('porcentual_desperdicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='desperdicio')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('ingrediente_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_10', to='cheff_app.ingredientes')),
                ('ingrediente_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_2', to='cheff_app.ingredientes')),
                ('ingrediente_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_3', to='cheff_app.ingredientes')),
                ('ingrediente_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_4', to='cheff_app.ingredientes')),
                ('ingrediente_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_5', to='cheff_app.ingredientes')),
                ('ingrediente_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_6', to='cheff_app.ingredientes')),
                ('ingrediente_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_7', to='cheff_app.ingredientes')),
                ('ingrediente_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_8', to='cheff_app.ingredientes')),
                ('ingrediente_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_9', to='cheff_app.ingredientes')),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.ingredientes')),
            ],
            options={
                'db_table': 'producto_elaborado',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_venta')),
                ('medida_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='medida_producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock')),
                ('desperdicio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desperdicio')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
            ],
            options={
                'db_table': 'producto_terminado',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='proveedor')),
                ('cuit', models.CharField(default='', max_length=50, verbose_name='cuit')),
                ('direccion', models.CharField(default='', max_length=50, verbose_name='direccion')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='haber')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='UnMedida',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('un_medida', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'un_medida',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('cant_pt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_pt')),
                ('cant_pe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_pe')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='importe')),
                ('codigo_pe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoelaborado')),
                ('codigo_pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoterminado')),
                ('insumo_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.insumos_mesa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.mesa')),
                ('moza_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.moza_o')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='un_medida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_10',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_10', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_2', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_3', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_4', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_5', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_6', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_7', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_8',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_8', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_9',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_9', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_base',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpte_nro', models.PositiveIntegerField(default=0, unique=True, verbose_name='cpte_nro')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='importe')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('ingredientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.ingredientes')),
                ('moza_o', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.moza_o')),
                ('producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoelaborado')),
                ('producto_terminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoterminado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.comprobante')),
            ],
            options={
                'db_table': 'operacion',
            },
        ),
        migrations.AddField(
            model_name='insumos_mesa',
            name='un_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='un_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
    ]
