# Generated by Django 3.2.2 on 2022-07-15 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=20, unique=True, verbose_name='tipo')),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='numero')),
                ('capacidad', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='capacidad')),
                ('descripcion', models.CharField(default='', max_length=60, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Moza_o',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('legajo', models.PositiveIntegerField(unique=True, verbose_name='legajo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='fecha_ingreso')),
                ('cuil', models.CharField(default='', max_length=80, verbose_name='cuil')),
                ('direccion', models.CharField(default='', max_length=80, verbose_name='direccion')),
                ('telefono', models.CharField(default='', max_length=80, verbose_name='telefono')),
            ],
            options={
                'db_table': 'moza_o',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='proveedor')),
                ('cuit', models.CharField(default='', max_length=50, verbose_name='cuit')),
                ('direccion', models.CharField(default='', max_length=50, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('e_mail', models.EmailField(default='', max_length=50, verbose_name='e_mail')),
                ('porc_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='porc_iva')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='UnMedida',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('un_medida', models.CharField(max_length=30, unique=True, verbose_name='un_medida')),
            ],
            options={
                'db_table': 'un_medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('descripcion', models.CharField(default='', max_length=80, verbose_name='descripcion')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_venta')),
                ('medida_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='medida_producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='stock')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('un_medida', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='CtaProv',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('cpte_nro', models.PositiveIntegerField(verbose_name='cpte_nro')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='iva')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe_total')),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='haber')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='saldo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.proveedor')),
                ('tipo_cpte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.comprobante')),
            ],
            options={
                'db_table': 'cta_prov',
            },
        ),
    ]
