# Generated by Django 3.2.2 on 2022-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctaprov',
            name='debe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='debe'),
        ),
    ]
