# Generated by Django 3.2.2 on 2022-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='medida_producto'),
        ),
    ]
