# Generated by Django 3.2.2 on 2022-06-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnMedida',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('un_medida', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'un_medida',
            },
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='desperdicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desperdicio'),
        ),
        migrations.CreateModel(
            name='ProductoElaborado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('descripcion', models.CharField(default='', max_length=80, verbose_name='descripcion')),
                ('imagen', models.ImageField(default='', null=True, upload_to='productos/', verbose_name='imagen')),
                ('porcentual_desperdicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='desperdicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('ingrediente_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_10', to='cheff_app.productoterminado')),
                ('ingrediente_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_2', to='cheff_app.productoterminado')),
                ('ingrediente_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_3', to='cheff_app.productoterminado')),
                ('ingrediente_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_4', to='cheff_app.productoterminado')),
                ('ingrediente_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_5', to='cheff_app.productoterminado')),
                ('ingrediente_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_6', to='cheff_app.productoterminado')),
                ('ingrediente_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_7', to='cheff_app.productoterminado')),
                ('ingrediente_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_8', to='cheff_app.productoterminado')),
                ('ingrediente_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_9', to='cheff_app.productoterminado')),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoterminado')),
            ],
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='medida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
    ]
