# Generated by Django 3.2.2 on 2022-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0002_auto_20220616_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantes',
            name='nombre',
            field=models.CharField(default='cpte', max_length=20, unique=True, verbose_name='cptes'),
        ),
        migrations.AlterModelTable(
            name='productoelaborado',
            table='producto_elaborado',
        ),
    ]
