# Generated by Django 3.2.2 on 2022-07-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0003_auto_20220718_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moza_o',
            name='nombre',
            field=models.CharField(default='dd/mm/aaaa', max_length=80, verbose_name='nombre'),
        ),
    ]
