# Generated by Django 3.2.2 on 2022-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0003_auto_20220616_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(default='', max_length=50, verbose_name='cuit'),
        ),
    ]
