# Generated by Django 3.2.2 on 2022-06-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0004_proveedor_cuit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprobantes',
            new_name='Comprobante',
        ),
        migrations.AlterModelTable(
            name='comprobante',
            table='comprobante',
        ),
    ]
