# Generated by Django 3.2.2 on 2022-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0005_auto_20220616_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoterminado',
            name='precio',
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_costo'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_venta'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='codigo',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo'),
        ),
    ]
