# Generated by Django 3.2.2 on 2022-06-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0006_auto_20220616_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminado',
            old_name='medida',
            new_name='un_medida',
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='medida_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='medida_producto'),
        ),
    ]
