# Generated by Django 3.2.2 on 2022-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0008_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='medida_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock'),
        ),
    ]
