# Generated by Django 3.2.2 on 2022-06-21 00:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0009_auto_20220620_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosMercaderia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpte_nro', models.PositiveIntegerField(default=0, unique=True, verbose_name='cpte_nro')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoterminado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.comprobante')),
            ],
        ),
    ]
