# Generated by Django 3.2.2 on 2022-06-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0012_alter_ingresosmercaderia_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosmercaderia',
            name='ingredientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.ingredientes'),
        ),
    ]
