# Generated by Django 3.2.2 on 2022-06-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0014_alter_ingresosmercaderia_cpte_nro'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientes',
            table='ingrediente',
        ),
    ]
