# Generated by Django 3.2.2 on 2022-06-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0015_alter_ingredientes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientes',
            table='ingredientes',
        ),
    ]
