# Generated by Django 3.2.2 on 2022-06-21 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0016_alter_ingredientes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos_Mesa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medida_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('un_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida')),
            ],
            options={
                'db_table': 'insumos_mesa',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='numero')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Moza_o',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='fecha_ingreso')),
                ('cuil', models.CharField(default='', max_length=80, verbose_name='cuil')),
                ('direccion', models.CharField(default='', max_length=80, verbose_name='direccion')),
                ('telefono', models.CharField(default='', max_length=80, verbose_name='telefono')),
            ],
            options={
                'db_table': 'moza_o',
            },
        ),
        migrations.AlterModelTable(
            name='ingresosmercaderia',
            table='ingresos_mercaderia',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
                ('codigo_pe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoelaborado')),
                ('codigo_pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.productoterminado')),
                ('insumo_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheff_app.insumos_mesa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.mesa')),
                ('moza_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.moza_o')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='moza_o',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.moza_o'),
        ),
    ]
