# Generated by Django 3.2.2 on 2022-06-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0017_auto_20220621_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cant_pe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_pe'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cant_pt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_pt'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='importe'),
        ),
    ]
