# Generated by Django 3.2.2 on 2022-06-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0019_auto_20220622_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debe'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='haber'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo'),
        ),
    ]
