# Generated by Django 3.2.2 on 2022-06-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0020_auto_20220622_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='moza_o',
        ),
        migrations.AddField(
            model_name='mesa',
            name='cant_comensales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='cant_comensales'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='descripcion',
            field=models.CharField(default='', max_length=60, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='moza_o',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.moza_o'),
        ),
    ]
