# Generated by Django 3.2.2 on 2022-06-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0021_auto_20220622_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_10'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_2'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_3'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_4'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_5'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_6'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_7'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_8'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_9'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='cant_ing_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cant_ing_base'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_10', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_2', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_3', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_4', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_5', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_6', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_7', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_8', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_9', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheff_app.ingredientes'),
        ),
    ]
