# Generated by Django 3.2.2 on 2022-06-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0022_auto_20220623_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_10',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_10', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_2', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_3', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_4', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_5', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_6', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_7', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_8',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_8', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_9',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='un_medida_9', to='cheff_app.unmedida'),
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='un_medida_base',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cheff_app.unmedida'),
        ),
    ]
