# Generated by Django 3.2.2 on 2022-06-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheff_app', '0023_auto_20220623_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_10', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_2', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_3', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_4', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_5', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_6', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_7', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_8', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='ingrediente_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_9', to='cheff_app.ingredientes'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='porcentual_desperdicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='desperdicio'),
        ),
    ]
